# Generated by Django 2.1.7 on 2019-03-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_body', models.TextField(default=None)),
                ('text_author', models.CharField(max_length=255)),
                ('text_name', models.CharField(max_length=255)),
                ('word_count', models.IntegerField(default=0)),
                ('genre_text', models.SmallIntegerField(default=0)),
                ('type_text', models.SmallIntegerField(default=0)),
                ('status', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
