# Generated by Django 2.1.7 on 2019-05-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='pos_tag',
            field=models.CharField(default='', max_length=255),
        ),
    ]
