# Generated by Django 2.1.7 on 2019-05-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='apertium_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
