# Generated by Django 2.1.7 on 2019-05-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_word_apertium_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='numeric',
            field=models.IntegerField(default=0),
        ),
    ]
