# Generated by Django 2.1.7 on 2019-05-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_word_numeric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordform', models.TextField(blank=True, null=True)),
                ('apertium_output', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(to='search.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='apertium_output',
        ),
        migrations.RemoveField(
            model_name='word',
            name='tags',
        ),
        migrations.AddField(
            model_name='word',
            name='wordforms',
            field=models.ManyToManyField(to='search.Wordform'),
        ),
    ]
