# Generated by Django 2.1.7 on 2019-05-16 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20190516_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='words',
        ),
        migrations.AddField(
            model_name='sentence',
            name='words',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search.Wordform'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='word',
            name='wordforms',
        ),
        migrations.AddField(
            model_name='word',
            name='wordforms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search.Wordform'),
            preserve_default=False,
        ),
    ]
