# Generated by Django 2.1.7 on 2019-05-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20190516_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='words',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='wordforms',
            new_name='wordform',
        ),
    ]
