# Generated by Django 2.1.7 on 2019-05-16 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20190516_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='word',
        ),
        migrations.RemoveField(
            model_name='word',
            name='wordform',
        ),
        migrations.AddField(
            model_name='word',
            name='sentence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search.Sentence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordform',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search.Word'),
            preserve_default=False,
        ),
    ]
