# Generated by Django 2.1.7 on 2019-05-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_auto_20190516_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordform',
            name='tags',
        ),
        migrations.AddField(
            model_name='wordform',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='search.Tag'),
            preserve_default=False,
        ),
    ]
