# Generated by Django 2.1.7 on 2019-05-17 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_auto_20190516_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordform',
            old_name='tags',
            new_name='tag',
        ),
    ]
