# Generated by Django 2.1.7 on 2019-05-17 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_auto_20190517_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordform',
            name='tag',
        ),
    ]
