# Generated by Django 2.1.7 on 2019-06-10 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_remove_wordform_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordform',
            name='sentence',
            field=models.ForeignKey(default=44, on_delete=django.db.models.deletion.CASCADE, to='search.Sentence'),
            preserve_default=False,
        ),
    ]
