# Generated by Django 2.1.7 on 2019-06-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_auto_20190613_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='eng_senetence',
            new_name='eng_sentence',
        ),
    ]
